org: tmaximini
app: serverless-jwt-authorizer

custom:
  secrets: ${file(secrets.json)}

service: serverless-jwt-authorizer
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    iamRoleStatements:
      Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        # - "dynamodb:DeleteItem"
    Resource: "arn:aws:dynamodb:eu-central-1:099822205767:table/Articles"
functions:
  verify-token:
    handler: functions/authorize.verifyToken

  me:
    handler: functions/users.me
    events:
      - http:
          path: me
          method: get
          cors: true
          authorizer:
            name: verify-token # execute this before !
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
  login:
    handler: functions/users.signIn
    events:
      - http:
          path: login
          method: post
          cors: true
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-test-table
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: hashedPassword
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
